# Generated by Django 4.1.3 on 2022-11-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_name',
            new_name='booking_date',
        ),
    ]
